# Generated by Django 6.1.2 on 2026-10-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reminder_text", models.TextField()),
                ("due_date", models.DateField()),
                ("is_sent", models.BooleanField(default=False)),
            ],
        ),
    ]
